name: azure_translation
description: A wrapper for interacting with Azure's translation API.
version: 0.1.0
# repository: https://github.com/my_org/my_repo

environment:
  sdk: ^3.0.6

# Add regular dependencies here.
dependencies:
  elegant: ^0.0.2
  http: ^1.1.0
  # path: ^1.8.0

dev_dependencies:
  dotenv: ^4.1.0
  lints: ^2.0.0
  test: ^1.21.0
